languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Heliacal Club"
# logo = "img/logo.png"
description = "The Free Spiritual Conmpendium"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Heliacal Club"
  image = "img/blowfish_logo.png"
  headline = "free for all; forever ☀️"
  bio = "Publications by Heliacal Club will always be free for everyone. We do not believe in selling or promoting regurgitated content. Each article is curated specially for spiritual evolution."
  links = [
     { email = "mailto:ignaziop@duck.com" },
     { akasha = "https://akasha.ghost.io/" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { facebook = "https://facebook.com/username" },
  #   { instagram = "https://instagram.com/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
    #   { telegram = "https://t.me/username" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
    { koji = "https://withkoji.com/@akasha/" },
   ]
